src/main/resources/META-INF/org.jbake.parser.TemplateEngines.properties

This is important for example when live editing (a plugin) in IntelliJ. This doesn't work with .thyme extension and the IntelliJ built-in debug webserver.

Thymeleaf templates are plain HTML files, they should be named .html

---

src/main/java/org/jbake/parser/MarkdownEngine.java

This change enhances the configuration of the markdown.extensions.
So far, you could just specify all the active extensions. With this
change, you can specify unwanted extensions as well.
For example:
markdown.extensions=ALL,-HARDWRAPS
activates all extensions with exception of the HARDWRAP extension

Markdown.extensions: Added STRIKETHROUGH, enhanced configuration of markdown.extensions: ALL,-HARDWRAPS

---

src/main/java/org/jbake/app/Asset.java
src/main/java/org/jbake/app/ConfigUtil.java
src/test/java/org/jbake/app/AssetTest.java

During normal usage I noticed an automatically created file ".DS_Store" was copied into destination folder. Of course it's not jbake's fault, but on the other hand you only have to open the assets folder using "Finder" to risk this file being created without one noticing.
So I thought it might be nice to have an option to simply ignore those automatically created (and usually hidden) files.

Enable asset copy to ignore hidden resources

---

pom.xml
src/main/java/org/jbake/launcher/Main.java

OrientDB uses java.util.logging.
The bridge routes the log messages from jul to slf4j.
See http://www.slf4j.org/legacy.html

Closes #205 - added jul-to-slf4j bridge

---

pom.xml
src/main/java/org/jbake/app/ConfigUtil.java
src/main/java/org/jbake/app/Crawler.java
src/main/resources/default.properties
src/test/java/org/jbake/app/CrawlerTest.java

New property `uri.noExtension` allows the user to specify a root folder for which "extensionless" URLs will be created. In practice, the file name is used as a folder and the actual file is generated as index.html inside that folder. `uri.noExtension` defaults to `false`, which does nothing.
For example:
If `uri.noExtension` is set to `/blog`, then after baking, the file `/blog/2014/03/26/post.md` would become `/output/blog/2014/03/26/post/index.html` and the URL would be `<DOMAIN>/blog/2014/03/26/post`.

Extensionless URLs

---

src/main/java/org/jbake/app/Crawler.java
src/main/java/org/jbake/app/DBUtil.java
src/main/java/org/jbake/app/Parser.java
src/main/java/org/jbake/app/Renderer.java
src/main/java/org/jbake/model/DocumentTypes.java
src/main/java/org/jbake/parser/AsciidoctorEngine.java
src/main/java/org/jbake/parser/Engines.java
src/main/java/org/jbake/parser/MarkupEngine.java
src/main/java/org/jbake/parser/ParserContext.java
src/main/java/org/jbake/parser/ParserEngine.java
src/main/java/org/jbake/template/AbstractTemplateEngine.java
src/main/java/org/jbake/template/TemplateEngines.java
src/test/java/org/jbake/app/CrawlerTest.java
src/test/java/org/jbake/app/GroovyRendererTest.java
src/test/java/org/jbake/app/RendererTest.java
src/test/java/org/jbake/app/ThymeleafRendererTest.java

I need to separate a little markup engine from the crawler code in order to insert jpeg engine into.
This change don't seems to break anything, and is only code move.

Preliminary refactoring

---

src/main/java/org/jbake/template/ThymeleafTemplateEngine.java

Currently the Thymeleaf  template engine is re-initialized for each and every generated page. Initializing the template engine is a costly operation, because this drops the resolved templates. When initializing the template engine for each page, all used templates must be resolved for each rendering operation. This greatly reduces rendering performance. Instead, the template engine should only be only re-initialized, if the template mode changes.
With this change, baking time for my relatively small recipe dramatically drops from over 13s to around 7s. But I expect an even more dramatic performance boost for larger scenarios.

Superfast baking with Thymeleaf

---

src/main/java/org/jbake/app/Asset.java
src/main/java/org/jbake/app/Oven.java
src/main/java/org/jbake/app/Renderer.java
src/main/java/org/jbake/launcher/Main.java

If jbake crashes with an exception, no detailed stack traces are reported. If  exceptions are thrown e.g. during rendering, these exceptions are caught and their messages are recorded. Afterwards, a fresh exception is thrown with all aggregated messages concatenated - so far so good. The problem is that the new exception has no linked cause making debugging a nightmare. It would be better to not record the messages but the exceptions themselves, build the new exception message from their messages, but at least link the first cause as cause of the new exception.
Besides that, it is good practice to link wrapped exceptions to their cause. Whenever one has the pattern 
```java
} catch (AException ex) {
throw new BException("...");
}
```
this should be re-written as 
```java
} catch …
```

Detailed errors with stack trace of the original problem

---

src/test/java/org/jbake/app/template/AbstractTemplateEngineRenderingTest.java
src/test/java/org/jbake/app/template/FreemarkerTemplateEngineRenderingTest.java
src/test/java/org/jbake/app/template/GroovyMarkupTemplateEngineRenderingTest.java
src/test/java/org/jbake/app/template/GroovyTemplateEngineRenderingTest.java
src/test/java/org/jbake/app/template/JadeTemplateEngineRenderingTest.java
src/test/java/org/jbake/app/template/ThymeleafTemplateEngineRenderingTest.java
src/test/resources/freemarkerTemplates/index.ftl
src/test/resources/freemarkerTemplates/page.ftl
src/test/resources/freemarkerTemplates/post.ftl

The FreemarkerTemplateEngineRenderingTest failed. Fixed template files and refactored the AbstractTemplateEngineRenderingTest a bit.

fixed broken template engine unit tests

---

src/main/resources/META-INF/services/org.jbake.render.RenderingTool
src/test/java/org/jbake/render/ServiceLoaderTest.java

Renamed provider-configuration file according to https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html and wrote a little test.

Fixed loading of RenderingTool Providers

---

src/main/java/org/jbake/parser/MarkupEngine.java
src/main/java/org/jbake/template/AbstractTemplateEngine.java

A small amount of refactoring:
- corrected a spelling
- introduced a constant to replace a magic string
- simplified some boolean logic
- moved some functionality into small methods.
This reveals a couple of small issues which I may get time to address in other pull requests:
- The 'isJson' method should probably be changed to be a little more robust in checking whether the contents is json
- The header processing logic looks like it could be moved into a class of its own

Minor refactoring

---

src/test/resources/groovyTemplates/archive.gsp
src/test/resources/groovyTemplates/feed.gsp
src/test/resources/groovyTemplates/index.gsp
src/test/resources/groovyTemplates/post.gsp
src/test/resources/groovyTemplates/tags.gsp

The [function `Date#format(java.lang.String)`](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Date.html#format(java.lang.String)) used in the GroovyTemplates uses the system Locale to format the date. When the Date format uses `MMMM` or `MMM` the name (resp. the short name) of the month is used.
This make the JBake build platform dependent (for example: the locale configuration on my machine is German and it is English on my CI Server)
In my opinion, for those cases, the complete form of the formatter should be used:
new java.text.SimpleDateFormat(<Pattern>, Locale.ENGLISH).format(<Date>)
This pull request makes the corresponding changes. If you prefer a different solution, I would be happy to implement it. Please provide some pointers in order for me to start.

(GroovyTemplates) Use English Locale in the date formatter

---

pom.xml
src/main/java/org/jbake/template/ThymeleafTemplateEngine.java
src/test/java/org/jbake/app/template/ThymeleafTemplateEngineRenderingTest.java

#262 Upgrade Thymeleaf to 3.0

---

pom.xml
src/main/assembly/assembly-example-project-groovy-mte.xml
src/main/java/org/jbake/app/Oven.java
src/main/resources/default.properties

Added an assembly description for the groovy-mte example project and the necessary executions.
Run ```jbake -i -t groovy-mte``` to initialize a new Project.
Closes #244

include example-project groovy-mte (Groovy MarkupTemplateEngine)

---

src/main/java/org/jbake/parser/MarkdownEngine.java
src/test/java/org/jbake/app/MdParserTest.java

In pegdown 1.6 we have new options to process markdown. I've added it to jbake

New options from pegdown 1.6

---

src/main/java/org/jbake/app/ContentStore.java
src/main/java/org/jbake/app/DBUtil.java
src/main/java/org/jbake/app/Oven.java

Using a local storage cache with `db.store=local` throws an exception
rerunning the bake task.
```
:bake FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':bake'.
> Cannot open local storage 'cache' with mode=rw
```
See [stacktrace](https://gist.github.com/ancho/a031859dd4a04f497c91a12a51c09c7f).

shutdown orient database after bake has finished.

---

src/main/scripts/jbake

useful when one plans to develop and release locally via maven package from one's fork; i.e.
$ ls -l ~/bin/jbake 
lrwxrwxrwx 1 user group 49 Okt 20 15:22 /home/user/bin/jbake -> /home/user/workspace/rels/jbake-2.5.0/bin/jbake
$ tail ~/.bashrc -n1
export PATH="${PATH}:${HOME}/bin"

Add support for symbolically linked launcher

---

pom.xml

Running
mvn clean package
[Log from master build](https://gist.github.com/lamvak/6726d6e07786755ec7c09b02bac259e8)
[Log from ignore_javadoc branch build](https://gist.github.com/lamvak/9f1b828c40f82c4cf95b2d56608e267a)
Of course, since javadoc is used for documentation, it would be better to just fix the issues. However this allows to build the package with current shape.

Ignore javadoc error on package

---

pom.xml
src/main/java/org/jbake/app/ContentStore.java
src/main/java/org/jbake/app/Renderer.java
src/main/java/org/jbake/template/model/TaggedDocumentsExtractor.java
src/main/resources/META-INF/org.jbake.template.ModelExtractors.properties

`org.jbake.app.Renderer#renderTags(String)` calls `ContentStore#getTags()` where it should call `ContentStore#getAllTags()` (IMHO), see #266 @jonbullock, WDYT?

Tag pages are created for documents of type post only

---

pom.xml
src/main/java/org/jbake/app/ContentStore.java
src/main/java/org/jbake/app/Renderer.java
src/main/java/org/jbake/model/DocumentAttributes.java
src/main/java/org/jbake/render/IndexRenderer.java
src/main/java/org/jbake/util/PagingHelper.java
src/test/java/org/jbake/app/ContentStoreTest.java
src/test/java/org/jbake/app/CrawlerTest.java
src/test/java/org/jbake/app/PaginationTest.java
src/test/java/org/jbake/app/template/AbstractTemplateEngineRenderingTest.java
src/test/java/org/jbake/app/template/FreemarkerTemplateEngineRenderingTest.java
src/test/java/org/jbake/render/ArchiveRendererTest.java
src/test/java/org/jbake/render/FeedRendererTest.java
src/test/java/org/jbake/render/IndexRendererTest.java
src/test/java/org/jbake/render/SitemapRendererTest.java
src/test/java/org/jbake/render/TagsRendererTest.java
src/test/java/org/jbake/render/support/MockCompositeConfiguration.java
src/test/java/org/jbake/util/PagingHelperTest.java
src/test/resources/content/blog/2016/another-post.html
src/test/resources/freemarkerTemplates/index.ftl

- adds `currentPageNumber` to the model to get the current page number
- adds `numberOfPages` to the model to get the total number of pages

fixes #310 - add nextFileName and previousFileName to the model

---

src/main/java/org/jbake/launcher/BakeWatcher.java
src/main/java/org/jbake/launcher/Baker.java
src/main/java/org/jbake/launcher/JettyServer.java
src/main/java/org/jbake/launcher/Main.java
src/test/java/org/jbake/launcher/MainTest.java

My goal for this pull request is to allow the `jbake/jbake-gradle-plugin` an API to start the `JettyServer`. While adding this functionality to the jbake-gradle-plugin, I observed a bug (#314) that prevents the `JettyServer` to start up with a custom output directory as well as providing the watcher with a custom source directory. The fix for this issue was fairly straightforward.
While adding this change to the `Main.run()` method, I recognized an opportunity to refactor the code to make it more testable. This allowed me to write tests for the failure cases I detected and provide fixes for them.

Improve testability of Main.java while fixing issue #314

---

src/main/java/org/jbake/app/Crawler.java
src/main/java/org/jbake/app/Renderer.java
src/main/java/org/jbake/render/DocumentsRenderer.java

* Replace StringBuffer with StringBuilder
* use append() instead of concatentaion

Use StringBuilder more consistently

---

src/main/java/org/jbake/app/Asset.java
src/main/java/org/jbake/app/Crawler.java
src/main/java/org/jbake/app/Oven.java
src/main/java/org/jbake/app/Renderer.java
src/main/java/org/jbake/model/DocumentTypes.java
src/test/java/org/jbake/app/AssetTest.java
src/test/java/org/jbake/app/CrawlerTest.java
src/test/java/org/jbake/app/GroovyRendererTest.java
src/test/java/org/jbake/app/OvenTest.java
src/test/java/org/jbake/app/RendererTest.java
src/test/java/org/jbake/app/ThymeleafRendererTest.java

These changes allow both relative and absolute paths for the configuration properties `asset.folder`, `content.folder` and `template.folder`.
This makes the configuration for the jbake-maven-plugin much more readable as you can use `<content.folder>${project.build.directory}/jbake/content</content.folder>` instead of something like `<content.folder>../../../target/jbake/content</content.folder>`.

Support absolute paths for asset, content and template folders

---

src/main/java/org/jbake/util/PagingHelper.java
src/test/java/org/jbake/app/template/FreemarkerTemplateEngineRenderingTest.java
src/test/java/org/jbake/util/PagingHelperTest.java

When index is paginated, previousFileName and nextFileName values are
added to content model. These values were including index.html in it.
For example, nextFileName value on first page was "2/index.html". It is
better to have values just as "2/" or "3/" etc. Corresponding test cases
have also been updated.
@ancho @jonbullock, Please take a look at this.

Exclude index.html from previousFileName and nextFileName values.

---

src/main/java/org/jbake/app/ContentStore.java
src/main/java/org/jbake/render/DocumentsRenderer.java
src/test/java/org/jbake/render/DocumentsRendererTest.java

This updates adds nextContent and previousContent data model in every document. This will allow the render previous post and next post type navigation on post/document page.
See the nav links at the bottom of below screenshot. Templates can use this as - 
```
<ul class="actions pagination">
<#if (post.previousContent)??> 
<li><a href="${content.rootpath}${post.previousContent.noExtensionUri!post.previousContent.uri}" 
class="button big previous">${content.previousContent.title}</a></li>
</#if>
<#if (post.nextContent)??> 
<li><a href="${content.rootpath}${post.nextContent.noExtensionUri!post.nextContent.uri}" 
class="button big next">${content.nextContent.title}</a></li>
</#if>
</ul>
```

Add document navigator data model

---

README.asciidoc
appveyor.yml
build.gradle
src/main/java/org/jbake/app/Crawler.java
src/main/java/org/jbake/app/Renderer.java
src/main/java/org/jbake/util/PagingHelper.java
src/smoke-test/java/org/jbake/BuiltInProjectsTest.java
src/test/java/org/jbake/app/AssetTest.java
src/test/java/org/jbake/launcher/MainTest.java
src/test/java/org/jbake/render/RendererTest.java
src/test/java/org/jbake/util/PagingHelperTest.java

This PR configures jbake to run CI tests on [appveyor](url), running two jobs for jdk 7 and 8.
I had to tweak the code a bit to get the tests pass. But it works.
The smoke tests are running fine executing the jbake binary with all built in example projects.
Have a look at the built results https://ci.appveyor.com/project/ancho/jbake
I added a [badge](https://github.com/jbake-org/jbake/compare/master...ancho:feature/appveyor-integration?expand=1#diff-d03d78a73f737f7943dde0f33e6e2b24R11) to the README. Don't forget to change the project URL.

enable ci tests on appveyor

---

build.gradle
gradle/application.gradle

* adds lib/* to the application classpath ( #230 )
* bumped asciidoctorj to 1.5.5
* added asciidoctorj-diagram 1.5.4 as distribution dependency
While I was working on including the lib directory, I was curious how to add library dependencies to the distribution only. So I added a new configuration called `dist` with asciidoctorj-diagram as an experiment.
That way people do not need to download the library manually but it isn't a dependency of jbake-core.
Addresses a part of #381. Not native but with asciidoctor.

pickup jars in distribution lib directory and add asciidoctorj-diagram as a distribution dependency

---

src/main/java/org/jbake/app/ContentStore.java
src/main/java/org/jbake/template/model/PublishedPostsExtractor.java
src/test/java/org/jbake/app/PaginationTest.java

Added additional methods to allow control over when the paging filter is applied. Removed paging on all_content as I believe it was a mistake being added to this as paging is currently based around 'post' type only. Kept the rest of the method signatures the same though.

Fixes #389

---

.travis.yml
build.gradle
jbake-core/src/main/java/org/jbake/app/ContentStore.java
jbake-core/src/test/java/org/jbake/app/ContentStoreIntegrationTest.java
jbake-core/src/test/java/org/jbake/app/ContentStoreTest.java
jbake-core/src/test/java/org/jbake/app/CrawlerTest.java
jbake-core/src/test/java/org/jbake/app/OvenTest.java
jbake-core/src/test/java/org/jbake/app/PaginationTest.java
jbake-core/src/test/java/org/jbake/app/template/AbstractTemplateEngineRenderingTest.java

A jdk9 travis build failed with an OutOfMemoryError.
https://travis-ci.org/jbake-org/jbake/jobs/352334663#L1403
Rearanged test setup to start only one orientdb per test class.
Adjusted Heapspace and MaxDirectMemorySize to fit travis environment.
Updated orientdb to 2.2.33 which include some fixes related to memory estimation in container environments. https://github.com/orientechnologies/orientdb/issues/7812

Fix travis jdk9 build -  java.lang.OutOfMemoryError: Direct buffer memory

---

build.gradle
jbake-core/build.gradle
jbake-core/src/test/java/org/jbake/FakeDocumentBuilder.java

As noted in #437 the size of the distribution package increased.
Modified dependencies of jbake-core to get it smaller.
* replaced orientdb-graphdb with orientdb-core
we don't use the graphs and do not need the server jar
* replaced flexmark-all with core and pegdown profile
we don't need converters and stuff like that
* excluded transitive junit dependency
make no sense at runtime
* updated
* asciidoctorj-diagram 1.5.4.1 -> 1.5.6
* flexmark 0.28.38 -> 0.32.18
* groovy 2.4.13 -> 2.4.14
* jsoup 1.10.3 -> 1.11.2
* mockito 2.13.0 -> 2.16.0

reduce distribution size

---

build.gradle
jbake-core/src/main/java/org/jbake/template/ThymeleafTemplateEngine.java

I noticed a strange behaviour baking a site using thymeleaf template engine.
https://gitlab.com/devlug/devlug-web
It was awful slow.
```
08:28:18.835 INFO  org.jbake.app.Oven - Baking finished!
08:28:18.835 INFO  org.jbake.app.Oven - Baked 86 items in 15048ms
```
I took a look at the memory consumption with visualvm.
When it hits the 500 MB mark the rendering process starts.
With the applied fix the overall bake time goes down do nearly 8 sec.
```
08:38:40.496 INFO  org.jbake.app.Oven - Baking finished!
08:38:40.496 INFO  org.jbake.app.Oven - Baked 86 items in 7894ms
```
And the memory consumption looks much better, too.
I had to update the gradle wrapper as bintray dropped TLS 1.0/1.1 support, which caused the java 7 build to fail on travis and appveyor. See …

Lazy evaluation of extractor values for ThymeleafTemplateEngine

---

.travis.yml

https://docs.travis-ci.com/user/languages/java/#using-java-10-and-later
unfortunately openjdk11 fails at present in contrast to the
documentation

add jdk 10 to travis build matrix

---

jbake-core/src/main/java/org/jbake/app/Crawler.java
jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java
jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java
jbake-core/src/main/java/org/jbake/app/configuration/JBakeProperty.java
jbake-core/src/main/resources/default.properties

Wraps image path update in config option

---

jbake-core/src/main/java/org/jbake/parser/MarkupEngine.java

Adds check to make sure header separator found demarcates metadata header, and ignores if separator is found in content itself.

Fixes #538

---

build.gradle
gradle/publishing.gradle
jbake-core/build.gradle
jbake-dist/build.gradle

The bintrayUpload task for the binary distribution was broken with >1.8.0 of the bintray gradle plugin.
This small modifications fix the problem.
run `./gradlew clean -PbintrayDryRun=true bU --info`
and expect an output like:
```
> Task :jbake-dist:bintrayUpload
Task ':jbake-dist:bintrayUpload' is not up-to-date because:
Task has not declared any outputs despite executing actions.
Gradle Bintray Plugin version: 1.8.4
Version 'jbake/binary/jbake/2.7.0-SNAPSHOT' does not exist. Attempting to create it...
(Dry run) Created version 'jbake/binary/jbake/2.7.0-SNAPSHOT'.
Uploading to https://api.bintray.com/content/jbake/binary/jbake/2.7.0-SNAPSHOT/./jbake-2.7.0-SNAPSHOT-bin.zip...
(Dry run) Uploaded to 'https://api.bintray.com/content/jbake/binary/jbake/2.7.0-SNAPSHOT/./jbake-2.7.0-SNAPSHOT-bin. …
```

fix jbake-dist upload to bintray

---

.travis.yml
build.gradle
gradle.properties

* update to groovy 2.5.3
* enable jdk 11 build at travis

update to groovy 2.5.3 for JDK 11 support

---

gradle/application.gradle

Why:
*  when running jbake on cli there is no easy way to configure logging
nor add additional jars.
This change addreses the need by:
* extend current searh/replace of scripts to add `pwd`/lib
and lib/logging
Note: I've tested the linux sh version on OSX, don't have a way
to test Windows nor pure linux right now but I have high confidence
that it will work :)

Add current dir lib/* and lib/logging to classpath

---

jbake-core/src/main/java/org/jbake/template/TemplateEngines.java

Lower loglevel to "WARN" as not all engines need to be loaded in all
circumstances.
This closes #567

Catch all classloading issues

---

BUILD.adoc
README.asciidoc
build.gradle
config/checkstyle/checkstyle.xml

A simple set of codestyle rules for jbake.
Uses default configurations for
* [Indentation](http://checkstyle.sourceforge.net/config_misc.html#Indentation)
* [AvoidStarImport](http://checkstyle.sourceforge.net/config_imports.html#AvoidStarImport)
* [NeedBraces](http://checkstyle.sourceforge.net/config_blocks.html#NeedBraces)
* [LeftCurly](http://checkstyle.sourceforge.net/config_blocks.html#LeftCurly) with `option=eol`
* [RightCurly](http://checkstyle.sourceforge.net/config_blocks.html#RightCurly)

add checkstyle rules

---

build.gradle
jbake-core/src/main/java/org/jbake/parser/MarkdownEngine.java
jbake-core/src/test/java/org/jbake/launcher/MainTest.java
jbake-dist/build.gradle

A last update for the 2.6.4 milestone.
Plugins:
* sonarqube 2.6.2 -> 2.7
* nebula optional-base 4.0.1 -> 5.0.0
Dependencies:
* asciidoctorj-diagram 1.5.10 -> 1.5.11
* flexmark 0.34.48 -> 0.40.8
* groovy 2.5.3 -> 2.5.5
* thymeleaf 3.0.9.RELEASE -> 3.0.11.RELEASE
* mockito 2.23.0 -> 2.24.0
* grgit 5.1.2.201810061102-r -> 5.2.1.201812262042-r

update dependencies compatible with jdk 7

---

build.gradle

makes it possible to configure `org.apache.commons` or
any 3rd party library using commons-logging with logback
closes #597

add jcl-over-slf4j bridge

---

jbake-core/src/test/java/org/jbake/app/AsciidocParserTest.java

validates that ascidoctor.attributes configuration works. See #616

add asciidoctor parser tests

---

.travis.yml
appveyor.yml
build.gradle
gradle.properties
jbake-dist/build.gradle

adds openjdk 14 test jobs for linux and macosx. moves coveralls job to "Quality Check" stage.
test logging configuration to print tests and stacktraces to the console.

cleanup and build against openjdk 14

---

jbake-core/src/main/java/org/jbake/app/ContentStore.java
jbake-core/src/test/java/org/jbake/app/ContentStoreTest.java

The ContentStore implementation assumes, that the document types are
valid identifiers, that can be used without quoting them. This limits
document types to "simplified identifiers". This changeset quotes the
identifiers and thus allows for example using a hyphen in the document
type.
This problem was observed when trying to update an older setup, that
was using types like "page-front", "page-noaside", "platform-tutorial".

Don't assume document types are valid identifiers in OrientDB

---

build.gradle
gradle.properties
gradle/application.gradle
gradle/maven-publishing.gradle
jbake-core/build.gradle
jbake-dist/build.gradle

Using the timestamp of the current repository HEAD and make sure the generated jar and zipfiles evaluate to the same checksums after rebuilding.

produce reproducible archives (distribution zip and jar files)

---

jbake-core/src/main/java/org/jbake/template/TemplateEngines.java

For the reasons presented in https://github.com/jbake-org/jbake/issues/634#issuecomment-827036102

Use lower log level to report missing template engine

---

jbake-core/src/main/java/org/jbake/launcher/Main.java

Wrap usage at 80 characters instead of 100

---

gradle.properties
jbake-core/build.gradle
jbake-core/src/main/java/org/jbake/app/Crawler.java
jbake-core/src/main/java/org/jbake/app/FileUtil.java
jbake-core/src/main/java/org/jbake/app/Oven.java
jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java
jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java
jbake-core/src/main/java/org/jbake/app/configuration/JBakeProperty.java
jbake-core/src/main/java/org/jbake/launcher/BakeWatcher.java
jbake-core/src/main/java/org/jbake/parser/YamlEngine.java
jbake-core/src/main/java/org/jbake/template/FreemarkerTemplateEngine.java
jbake-core/src/main/java/org/jbake/template/model/AllContentExtractor.java
jbake-core/src/main/java/org/jbake/template/model/DataExtractor.java
jbake-core/src/main/java/org/jbake/util/DataFileUtil.java
jbake-core/src/main/resources/META-INF/org.jbake.parser.MarkupEngines.properties
jbake-core/src/main/resources/META-INF/org.jbake.template.ModelExtractors.properties
jbake-core/src/main/resources/default.properties
jbake-core/src/test/java/org/jbake/app/CrawlerTest.java
jbake-core/src/test/java/org/jbake/template/ModelExtractorsTest.java
jbake-core/src/test/resources/fixture/data/videos.yaml

Resolves #680 
Analogous to feature in Awestruct, exposes data structures defined in YAML files for use within template files. Different to content files in that existence of data file doesn't automatically mean you want to produce 1-to-1 mapping with output file, hence the need to define new folder for these files.

Add support for data files specifically in YAML format

---

gradle.properties
jbake-core/build.gradle
jbake-core/src/main/java/org/jbake/app/ContentStore.java
jbake-core/src/main/java/org/jbake/app/JBakeException.java
jbake-core/src/main/java/org/jbake/app/configuration/ConfigUtil.java
jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfigurationInspector.java
jbake-core/src/main/java/org/jbake/launcher/Baker.java
jbake-core/src/main/java/org/jbake/launcher/JettyServer.java
jbake-core/src/main/java/org/jbake/launcher/LaunchOptions.java
jbake-core/src/main/java/org/jbake/launcher/Main.java
jbake-core/src/main/java/org/jbake/launcher/SystemExit.java
jbake-core/src/test/java/org/jbake/launcher/LaunchOptionsTest.java
jbake-core/src/test/java/org/jbake/launcher/MainTest.java

using https://github.com/remkop/picocli as a replacement for args4j.

switch to picocli

---

jbake-core/src/main/java/org/jbake/app/ConfigUtil.java
jbake-core/src/main/java/org/jbake/app/Renderer.java
jbake-core/src/main/java/org/jbake/render/Error404Renderer.java
jbake-core/src/main/resources/META-INF/services/org.jbake.render.RenderingTool
jbake-core/src/main/resources/default.properties
jbake-core/src/test/java/org/jbake/render/Error404RendererTest.java
jbake-core/src/test/resources/fixture/freemarkerTemplates/error404.ftl
jbake-core/src/test/resources/fixture/groovyMarkupTemplates/error404.tpl
jbake-core/src/test/resources/fixture/groovyTemplates/error404.gsp
jbake-core/src/test/resources/fixture/jadeTemplates/error404.jade
jbake-core/src/test/resources/fixture/jbake.properties
jbake-core/src/test/resources/fixture/thymeleafTemplates/error404.thyme

This PR tries to close #365. This PR stands good on tests against core functionality, but fails on dist test. I assume that happens because there is no standard 404 template in example repositories. I have quickly written 404 templates for all template engines that are present in /fixture folder in test package.

Fix #365 issue: add default 404 file generation

---

Dockerfile
README.asciidoc

NOTE: Docker image timezone is _UTC_. This may affect the date and time expected in output content. To set different timezone, add `TZ` environment variable and set value to required https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[timezone^]. 
Example - `docker run --rm -u jbake -e TZ=America/New_York -v "$PWD":/mnt/site jbake/jbake:latest`

Allow setting docker image timezone by env variable

---

jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java
jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java
jbake-core/src/main/java/org/jbake/app/configuration/PropertyList.java
jbake-core/src/main/java/org/jbake/template/FreemarkerTemplateEngine.java

Allows you to override the time zone used to display date and time in Freemarker templates.

Fixes #726 - Sets TimeZone for Freemarker template engine

---

gradle/application.gradle

https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
> On the Git protocol side, unencrypted git://...
> We’ll be disabling support for this protocol.

Change protocol used to clone examples

---

.travis.yml
appveyor.yml
build.gradle
buildSrc/src/main/groovy/org/jbake/convention/org.jbake.convention.java-common.gradle
gradle.properties
gradle/github-releases.gradle
jbake-core/build.gradle
jbake-core/src/main/java/org/jbake/app/Asset.java
jbake-dist/build.gradle

As the distribution package of jbake does deliver a writable logback.xml
we need to fix this immediatly.
See https://jira.qos.ch/browse/LOGBACK-1591 and [News from 14th of December](http://logback.qos.ch/news.html)

security update logback, other dependency updates + upgrade to gradle 7

---

jbake-maven-plugin/src/main/java/org/jbake/maven/util/DirWatcher.java

Use blocking method rather than the throwing one

---

jbake-core/build.gradle

I just build JBake from source by run `./gradlew clean build distZip`, and run jbake command in the terminal, I got the following:
```
➜  jbake git:(ds) jbake 
JBake v${jbakeVersion} (${timestamp} ${gitHash}#) [http://jbake.org]
```
It seems that build process did not expand variables defined in default.properties. 
```
version=v${jbakeVersion}
build.timestamp=${timestamp}
git.hash=${gitHash}
```
I retried the build by setting `duplicatesStrategy = DuplicatesStrategy.FAIL`, then it failed.   
But use `duplicatesStrategy = DuplicatesStrategy.INHERIT`,  the build process complains 
```
Entry default.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.3.3/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStr …
```

Change DuplicatesStrategy from EXCLUDE to INCLUDE

---

jbake-core/src/main/java/org/jbake/app/ContentStore.java
jbake-core/src/test/java/org/jbake/app/CrawlerTest.java
jbake-core/src/test/resources/fixture/data/authors.yaml

Fixes #747 - Force the OrientDB type rather than let OrientDB decide.

Resolves #747 - OTrackedMap returned for contents of data file

---

gradle.properties

This fixes `java.lang.UnsatisfiedLinkError` thrown by jbake-maven-plugin 2.7.0-rc.6 on Apple's M1 hardware (see #769).
The problem was caused by an older version of JRuby (a dependency of AsciidoctorJ) that does not support macos-aarch64. By upgrading AsciidoctorJ to the latest version, a newer version of JRuby supporting M1 is used, and `java.lang.UnsatisfiedLinkError` is no longer thrown.
Fixes #769.

Fix java.lang.UnsatisfiedLinkError thrown on Apple M1
