src/main/java/org/jbake/app/JBakeException.java, src/main/java/org/jbake/app/Oven.java, src/main/java/org/jbake/launcher/JBakeException.java, src/main/java/org/jbake/launcher/Main.java
=> Remove System.exit calls, add JBakeException, fix #167

src/main/java/org/jbake/app/ContentStore.java, src/main/java/org/jbake/app/Crawler.java, src/main/java/org/jbake/app/DBUtil.java, src/main/java/org/jbake/app/Oven.java, src/main/java/org/jbake/app/Renderer.java, src/main/java/org/jbake/template/AbstractTemplateEngine.java, src/main/java/org/jbake/template/DelegatingTemplateEngine.java, src/main/java/org/jbake/template/FreemarkerTemplateEngine.java, src/main/java/org/jbake/template/GroovyTemplateEngine.java, src/main/java/org/jbake/template/TemplateEngines.java, src/main/java/org/jbake/template/ThymeleafTemplateEngine.java, src/test/java/org/jbake/app/CrawlerTest.java, src/test/java/org/jbake/app/GroovyRendererTest.java, src/test/java/org/jbake/app/RendererTest.java, src/test/java/org/jbake/app/ThymeleafRendererTest.java
This branch moves all DB-related code behind a facade, ContentStore. This work lays the groundwork for implementing the pagination feature so many have requested.
=> ContentStore

src/main/java/org/jbake/app/Asset.java, src/main/java/org/jbake/app/ConfigUtil.java, src/main/java/org/jbake/app/Oven.java, src/test/java/org/jbake/app/AssetTest.java
As discussed in #194 and requested there, here's the PR
=> API restore

pom.xml, src/main/java/org/jbake/template/ThymeleafTemplateEngine.java
=> Feature use_thyme_extension

pom.xml, src/main/assembly/assembly-example-project-pebble.xml, src/main/java/org/jbake/template/PebbleTemplateEngine.java, src/main/resources/META-INF/org.jbake.parser.TemplateEngines.properties, src/test/java/org/jbake/app/PebbleRendererTest.java, src/test/resources/pebbleTemplates/allcontent.pebble, src/test/resources/pebbleTemplates/archive.pebble, src/test/resources/pebbleTemplates/base.pebble, src/test/resources/pebbleTemplates/feed.pebble, src/test/resources/pebbleTemplates/footer.pebble, src/test/resources/pebbleTemplates/header.pebble, src/test/resources/pebbleTemplates/index.pebble, src/test/resources/pebbleTemplates/menu.pebble, src/test/resources/pebbleTemplates/page.pebble, src/test/resources/pebbleTemplates/post.pebble, src/test/resources/pebbleTemplates/sitemap.pebble, src/test/resources/pebbleTemplates/tags.pebble
I'm not sure if you guys are interested but I added support for a template engine called [Pebble](http://www.mitchellbosecke.com/pebble).
=> Added support for Pebble template engine

pom.xml, src/main/assembly/assembly-example-project-jade.xml, src/main/java/org/jbake/template/JadeTemplateEngine.java, src/main/resources/META-INF/org.jbake.parser.TemplateEngines.properties, src/test/java/org/jbake/app/JadeRendererTest.java, src/test/resources/jadeTemplates/archive.jade, src/test/resources/jadeTemplates/feed.jade, src/test/resources/jadeTemplates/footer.jade, src/test/resources/jadeTemplates/header.jade, src/test/resources/jadeTemplates/index.jade, src/test/resources/jadeTemplates/layout.jade, src/test/resources/jadeTemplates/page.jade, src/test/resources/jadeTemplates/post.jade, src/test/resources/jadeTemplates/sitemap.jade, src/test/resources/jadeTemplates/tags.jade
Based on https://github.com/neuland/jade4j
=> Jade template engine implementation

pom.xml, src/main/java/org/jbake/app/DBUtil.java, src/main/java/org/jbake/app/Oven.java, src/main/java/org/jbake/launcher/LaunchOptions.java, src/main/java/org/jbake/parser/AsciidoctorEngine.java, src/main/java/org/jbake/parser/MarkupEngine.java, src/main/java/org/jbake/render/ArchiveRenderer.java, src/main/java/org/jbake/render/FeedRenderer.java, src/main/java/org/jbake/render/IndexRenderer.java, src/main/java/org/jbake/render/SitemapRenderer.java, src/main/java/org/jbake/render/TagsRenderer.java, src/main/java/org/jbake/template/AbstractTemplateEngine.java, src/main/java/org/jbake/template/DelegatingTemplateEngine.java, src/main/java/org/jbake/template/FreemarkerTemplateEngine.java, src/main/java/org/jbake/template/GroovyMarkupTemplateEngine.java, src/main/java/org/jbake/template/GroovyTemplateEngine.java, src/main/java/org/jbake/template/JadeTemplateEngine.java, src/main/java/org/jbake/template/ModelExtractors.java, src/main/java/org/jbake/template/TemplateEngines.java
=> Clean up and Asciidoctorj version change

pom.xml, src/main/java/org/jbake/parser/AsciidoctorEngine.java
Enable gemPath and requires properties when setting up asciidoctor engine. Fixes #267
=> Enable gemPath and requires properties on Asciidoctor

ROADMAP.txt
=> Updated link in ROADMAP.txt

src/main/java/org/jbake/app/ConfigUtil.java, src/main/java/org/jbake/app/Crawler.java, src/main/java/org/jbake/app/Renderer.java, src/main/java/org/jbake/parser/AsciidoctorEngine.java, src/main/java/org/jbake/template/TemplateEngineAdapter.java, src/test/java/org/jbake/app/AssetTest.java, src/test/java/org/jbake/app/CrawlerTest.java, src/test/java/org/jbake/app/PaginationTest.java, src/test/java/org/jbake/app/template/AbstractTemplateEngineRenderingTest.java
Some small code improvements based on the suggestions by IntelliJ.
=> Some small code improvements.

src/main/scripts/jbake
=> Fixed #329: Suppress the error message 'realpath: command not found'

src/main/java/org/jbake/parser/MarkupEngine.java
=> Fixes #257

src/main/java/org/jbake/app/Asset.java, src/main/java/org/jbake/app/Crawler.java, src/main/java/org/jbake/app/Oven.java, src/main/java/org/jbake/app/Renderer.java, src/main/java/org/jbake/model/DocumentTypes.java, src/test/java/org/jbake/app/AssetTest.java, src/test/java/org/jbake/app/CrawlerTest.java, src/test/java/org/jbake/app/OvenTest.java, src/test/resources/freemarkerTemplates/allcontent.ftl
Brought PR #229 up to date with master.
=> Manually merged in #229 

src/main/java/org/jbake/app/ConfigUtil.java, src/main/java/org/jbake/parser/MarkupEngine.java, src/test/java/org/jbake/app/ParserTest.java
Brought PR #279 up to date with master.
=> Manually merged in PR #279

src/main/java/org/jbake/app/Renderer.java, src/main/java/org/jbake/util/PagingHelper.java, src/test/java/org/jbake/app/template/FreemarkerTemplateEngineRenderingTest.java, src/test/java/org/jbake/util/PagingHelperTest.java
Brought PR #313 up to date with master.
=> Manually merged in PR #313

pom.xml, src/main/java/org/jbake/app/ContentStore.java, src/main/java/org/jbake/app/Renderer.java, src/main/java/org/jbake/model/DocumentAttributes.java, src/main/java/org/jbake/render/IndexRenderer.java, src/main/java/org/jbake/util/PagingHelper.java, src/test/java/org/jbake/app/ContentStoreTest.java, src/test/java/org/jbake/app/CrawlerTest.java, src/test/java/org/jbake/app/PaginationTest.java, src/test/java/org/jbake/app/template/AbstractTemplateEngineRenderingTest.java, src/test/java/org/jbake/app/template/FreemarkerTemplateEngineRenderingTest.java, src/test/java/org/jbake/render/ArchiveRendererTest.java, src/test/java/org/jbake/render/FeedRendererTest.java, src/test/java/org/jbake/render/IndexRendererTest.java, src/test/java/org/jbake/render/SitemapRendererTest.java, src/test/java/org/jbake/render/TagsRendererTest.java, src/test/java/org/jbake/render/support/MockCompositeConfiguration.java, src/test/java/org/jbake/util/PagingHelperTest.java, src/test/resources/content/blog/2016/another-post.html, src/test/resources/freemarkerTemplates/index.ftl
The first index.html is rendered into the root directory.
Following paginated pages are put into subfolders per page like 1/index.html, 2/index.html etc.
=>  paginate into subfolders

pom.xml, src/main/java/org/jbake/app/Asset.java, src/main/java/org/jbake/app/ConfigUtil.java, src/main/java/org/jbake/app/Crawler.java, src/main/java/org/jbake/app/DBUtil.java, src/main/java/org/jbake/app/FileUtil.java, src/main/java/org/jbake/app/Oven.java, src/main/java/org/jbake/app/Parser.java, src/main/java/org/jbake/app/Renderer.java, src/main/java/org/jbake/app/ZipUtil.java, src/main/java/org/jbake/launcher/Init.java, src/main/java/org/jbake/launcher/JettyServer.java, src/main/java/org/jbake/launcher/Main.java, src/main/java/org/jbake/model/DocumentTypes.java, src/main/java/org/jbake/template/GroovyMarkupTemplateEngine.java, src/main/java/org/jbake/template/ModelExtractors.java, src/main/java/org/jbake/template/TemplateEngineAdapter.java, src/main/java/org/jbake/template/TemplateEngines.java, src/main/java/org/jbake/template/ThymeleafTemplateEngine.java
Brought PR #319 up to date with master.
=> Manually merged in PR #319

pom.xml, src/main/java/org/jbake/app/Asset.java, src/main/java/org/jbake/app/ConfigUtil.java, src/main/java/org/jbake/app/Crawler.java, src/main/java/org/jbake/app/DBUtil.java, src/main/java/org/jbake/app/FileUtil.java, src/main/java/org/jbake/app/Oven.java, src/main/java/org/jbake/app/Parser.java, src/main/java/org/jbake/app/Renderer.java, src/main/java/org/jbake/app/ZipUtil.java, src/main/java/org/jbake/launcher/Init.java, src/main/java/org/jbake/launcher/JettyServer.java, src/main/java/org/jbake/launcher/Main.java, src/main/java/org/jbake/model/DocumentTypes.java, src/main/java/org/jbake/template/GroovyMarkupTemplateEngine.java, src/main/java/org/jbake/template/ModelExtractors.java, src/main/java/org/jbake/template/TemplateEngineAdapter.java, src/main/java/org/jbake/template/TemplateEngines.java, src/main/java/org/jbake/template/ThymeleafTemplateEngine.java
Followup on #309 
See log from build with Java 7 https://gist.github.com/lamvak/5bdc1f50775d1d1fc0b62ae707d85dfd and Java 8 https://gist.github.com/lamvak/b252b0b7045bb16251473efd64dfe2e6
=> Convert Javadoc to be compatible with strict Java 8 build

pom.xml, src/main/java/org/jbake/app/ContentStore.java, src/main/java/org/jbake/model/DocumentAttributes.java, src/main/scripts/jbake, src/main/scripts/jbake.bat, src/test/java/org/jbake/FakeDocumentBuilder.java, src/test/java/org/jbake/app/ContentStoreTest.java, src/test/java/org/jbake/app/PaginationTest.java
Brought PR #337 up to date with master.
=> Manually merged in PR #337

pom.xml, src/main/java/org/jbake/app/ContentStore.java, src/main/java/org/jbake/model/DocumentAttributes.java, src/main/scripts/jbake, src/main/scripts/jbake.bat, src/test/java/org/jbake/FakeDocumentBuilder.java, src/test/java/org/jbake/app/ContentStoreTest.java, src/test/java/org/jbake/app/PaginationTest.java
* added -XX:MaxDirectMemorySize=1024m to jbake and jbake.bat script, to prevent warning from orientdb
closes #318
=> update orientdb to 2.2.15

.travis.yml, README.asciidoc
Updated README and IRC room for build notifications.
=> Gradle clean up work

BUILD.adoc, CONTRIBUTING.asciidoc, README.asciidoc
Please review my distilled documentation and search for bad spelling and grammar :)
=> documentation about how to test, build and deploy jbake

README.asciidoc
Added gitter chat badge on the read me page.
=> Added Gitter chat badge

src/main/java/org/jbake/app/Crawler.java, src/main/java/org/jbake/template/FreemarkerTemplateEngine.java, src/test/java/org/jbake/app/template/FreemarkerTemplateEngineRenderingTest.java, src/test/resources/fixture/freemarkerTemplates/index.ftl
Manually merged in PR #358 to resolve conflict.
=> Manually merged in PR #358

src/main/java/org/jbake/app/Crawler.java, src/main/java/org/jbake/app/Renderer.java, src/test/java/org/jbake/app/CrawlerTest.java
Fixes Issue #360 for Extensionless URI and paginated index pages.
=> Corrected Rootpath for extension less uri and paginated indices.

src/main/java/org/jbake/launcher/BakeWatcher.java
=> Extended JBake watch mode to template and asset folder

build.gradle, gradle/application.gradle
Manually merged in PR #385 to resolve conflict.
=> Manually merged in PR #385

src/main/java/org/jbake/app/ConfigUtil.java, src/main/java/org/jbake/launcher/Main.java
Only displays warning if bake or serve commands are used.
=> Fixes #206

.travis.yml
Updated Travis CI configuration to notify on Gitter Team room.
=> Added Gitter team room notifications for TravisCI

src/main/java/org/jbake/template/ThymeleafTemplateEngine.java
Added support for lazy loading of variables.
=> Fixes #295

build.gradle
=> Upgraded flexmark-java to v0.27.0

jbake-core/src/main/java/org/jbake/template/AbstractTemplateEngine.java, jbake-core/src/main/java/org/jbake/template/ThymeleafTemplateEngine.java, jbake-core/src/test/java/org/jbake/app/template/AbstractTemplateEngineRenderingTest.java, jbake-core/src/test/java/org/jbake/app/template/FreemarkerTemplateEngineRenderingTest.java, jbake-core/src/test/resources/fixture/groovyMarkupTemplates/index.tpl, jbake-core/src/test/resources/fixture/groovyTemplates/index.gsp, jbake-core/src/test/resources/fixture/jadeTemplates/index.jade, jbake-core/src/test/resources/fixture/thymeleafTemplates/index.thyme
=> fix access to db model in Thymeleaf templates

jbake-core/src/main/java/org/jbake/parser/MarkupEngine.java
Re-worded warning log message.
=> Fixes #441

jbake-core/src/main/resources/default.properties
Updated comment listing values for db.store option.
=> Fix for #439

BUILD.adoc
=> align build doc with current setup

build.gradle, jbake-core/build.gradle, jbake-core/src/main/java/org/jbake/parser/MarkupEngine.java
Fixes #437 
Implemented Nebula plugin to enable support for optional flag on certain dependencies.
=> Fixes #437

.travis.yml, build.gradle, gradle/sonarqube.gradle, jbake-core/build.gradle, jbake-core/src/main/java/org/jbake/app/Crawler.java, jbake-core/src/main/java/org/jbake/app/DocumentList.java, jbake-core/src/main/java/org/jbake/app/Parser.java, jbake-core/src/main/java/org/jbake/app/Renderer.java, jbake-core/src/main/java/org/jbake/model/DocumentTypeUtils.java, jbake-core/src/main/java/org/jbake/model/DocumentTypes.java, jbake-core/src/main/java/org/jbake/render/IndexRenderer.java, jbake-core/src/main/java/org/jbake/template/ModelExtractor.java, jbake-core/src/main/java/org/jbake/template/model/TagsExtractor.java, jbake-core/src/main/java/org/jbake/util/PagingHelper.java, jbake-core/src/test/java/org/jbake/util/PagingHelperTest.java
=> Manually merged in #430

.travis.yml, build.gradle, gradle/sonarqube.gradle, jbake-core/build.gradle, jbake-core/src/main/java/org/jbake/app/ContentStore.java, jbake-core/src/main/java/org/jbake/app/Crawler.java, jbake-core/src/main/java/org/jbake/app/DocumentList.java, jbake-core/src/main/java/org/jbake/app/Parser.java, jbake-core/src/main/java/org/jbake/app/Renderer.java, jbake-core/src/main/java/org/jbake/model/DocumentTypeUtils.java, jbake-core/src/main/java/org/jbake/model/DocumentTypes.java, jbake-core/src/main/java/org/jbake/render/IndexRenderer.java, jbake-core/src/main/java/org/jbake/template/ModelExtractor.java, jbake-core/src/main/java/org/jbake/template/model/TagsExtractor.java, jbake-core/src/main/java/org/jbake/util/PagingHelper.java, jbake-core/src/test/java/org/jbake/util/PagingHelperTest.java
This is an attempt to address #428 
Configured gradle build and travis. Fixed some sonar issues to see what happens.
We are using the stage beta feature now. Added a Quality check stage which runs the sonarqube task
if Testing stage was successful.
=> run sonar scanner and report with travis. enable pull-request comments

gradle/sdkman.gradle
Updated candidate name and download URL pattern.
=> Closes #453 - SDKMAN Gradle plugin

jbake-core/src/main/java/org/jbake/app/FileUtil.java, jbake-core/src/main/java/org/jbake/app/ZipUtil.java
Updated code to use try-with-resources statement.
=> Fixes #456

README.asciidoc
Update dependency of markdown in README.asciidoc
=> Update dependency in README.asciidoc

build.gradle
Fixes a couple of issues of which I am affected by one.
https://jsoup.org/news/release-1.11.3
=> Upgrade jsoup, micro

jbake-core/src/main/java/org/jbake/app/Crawler.java
Fixes https://github.com/jbake-org/jbake/issues/499
=> Fix #499 file names encoding.

jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeProperty.java, jbake-core/src/main/java/org/jbake/util/HtmlUtil.java, jbake-core/src/main/resources/default.properties, jbake-core/src/test/java/org/jbake/util/HtmlUtilTest.java
=> Merged in #459 and addressed code review suggestions - take 2

gradle/wrapper/gradle-wrapper.properties, jbake-core/build.gradle, jbake-dist/build.gradle, jbake-dist/src/smoke-test/java/org/jbake/BinaryRunner.java, jbake-dist/src/smoke-test/java/org/jbake/BuiltInProjectsTest.java, jbake-dist/src/smoke-test/java/org/jbake/ProjectWebsiteTest.java
=> temporary jruby dependency update

jbake-core/src/main/java/org/jbake/util/HtmlUtil.java, jbake-core/src/test/java/org/jbake/util/HtmlUtilTest.java
=> fix relative image source transformation

jbake-core/src/main/java/org/jbake/util/DebugUtil.java, jbake-core/src/test/java/org/jbake/app/DebugUtilTest.java
=> Moved DebugUtil class to util package

jbake-core/src/main/java/org/jbake/app/Crawler.java
The potential exceptions should be caught in this place to capture the context.
=> Wrap Crawler iteration into a try/catch

jbake-core/src/main/java/org/jbake/app/ContentStore.java
A small refactoring to make it a bit more readable.
=> Reoder content store

build.gradle
=> Fixes #566

build.gradle, jbake-core/build.gradle, jbake-core/src/main/java/org/jbake/template/PebbleTemplateEngine.java, jbake-core/src/main/resources/META-INF/org.jbake.parser.TemplateEngines.properties, jbake-core/src/test/java/org/jbake/app/template/PebbleTemplateEngineRenderingTest.java, jbake-core/src/test/resources/fixture/pebbleTemplates/archive.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/base.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/feed.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/footer.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/header.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/index.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/menu.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/page.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/post.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/sitemap.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/tags-index.pebble, jbake-core/src/test/resources/fixture/pebbleTemplates/tags.pebble
=> Restores Pebble template engine support

jbake-core/src/main/java/org/jbake/app/configuration/ConfigUtil.java
=> set path to default.properties directly from classloader

.travis.yml, build.gradle, gradle/sonarqube.gradle, jbake-core/src/main/java/org/jbake/parser/MarkupEngine.java, jbake-core/src/test/java/org/jbake/app/AsciidocParserTest.java, jbake-core/src/test/java/org/jbake/app/ParserTest.java
=> sanitize header keys and values

README.asciidoc
=> Updated links for Travis

build.gradle, jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfigurationFactory.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeProperty.java, jbake-core/src/main/java/org/jbake/launcher/JettyServer.java, jbake-core/src/main/java/org/jbake/launcher/Main.java, jbake-core/src/main/resources/default.properties, jbake-core/src/test/java/org/jbake/app/configuration/JBakeConfigurationFactoryTest.java, jbake-core/src/test/java/org/jbake/launcher/JettyServerTest.java, jbake-core/src/test/java/org/jbake/launcher/MainTest.java
New configuration attributes:
* server.hostname = localhost
* server.contextPath = /
closes #641
=> make jetty server context path and host configurable

README.asciidoc
Reorganised badges.
Removed header duplication.
=> Replaced Bintray download badge with one for GitHub

jbake-core/src/main/java/org/jbake/launcher/JettyServer.java
=> add index.html to the list of known welcome files for jetty

.dockerignore, Dockerfile, README.asciidoc
Resolves jbake-org/jbake-docker-image#2 jbake-org/jbake-docker-image#3
=> Added Dockerfile and updated README

gradle.properties
Set version for v2.6.7 release.
=> Release v2.6.7

jbake-core/src/main/java/org/jbake/render/DocumentsRenderer.java, jbake-core/src/test/java/org/jbake/render/DocumentsRendererTest.java
excludes draft posts from navigation
=> jbake issue #652: prev/next post navigation only uses published posts

jbake-core/build.gradle, jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeProperty.java, jbake-core/src/main/java/org/jbake/launcher/Main.java, jbake-core/src/main/resources/default.properties
Uses grgit to retrieve head and corresponding abbreviatedId
Closes #675
=> (feat) Output abbreviated git hash during CLI execution #675

build.gradle, gradle.properties, gradle/github-releases.gradle, jbake-core/build.gradle, jbake-dist/build.gradle
create sha256 checksum files after distZip and add them to the github release
closes #677
=> create sha256 checksum files

jbake-core/src/main/java/org/jbake/app/configuration/ConfigUtil.java, jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfigurationFactory.java, jbake-core/src/main/java/org/jbake/launcher/Main.java, jbake-core/src/test/java/org/jbake/app/configuration/JBakeConfigurationFactoryTest.java, jbake-core/src/test/java/org/jbake/launcher/MainTest.java
Added extra method so build plugins don't need to depend on Apache Commons Configuration library.
=> Change config interface to simplify build plugins

jbake-core/src/main/java/org/jbake/app/Renderer.java, jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java, jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java, jbake-core/src/test/java/org/jbake/app/configuration/ConfigUtilTest.java, jbake-core/src/test/resources/fixture/content/team.html, jbake-core/src/test/resources/fixture/groovyMarkupTemplates/special/team.tpl, jbake-core/src/test/resources/fixture/jbake.properties
=> Fix to allow templates to be stored in folders

jbake-core/src/main/java/org/jbake/render/DocumentsRenderer.java, jbake-core/src/test/java/org/jbake/render/DocumentsRendererTest.java
=> Fix for next/prev references pulling in different data types

jbake-core/src/main/java/org/jbake/render/DocumentsRenderer.java
=> Resolve bug where next content always null

CONTRIBUTING.asciidoc
Minor update to the contributing documentation as raised in #723.
=> Documentation - contribution document updated to reflect support for Java 8

gradle.properties
=> Updated version for 2.7.0-rc.6 release
